import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'pt';

interface Translations {
  [key: string]: {
    [key in Language]: string;
  };
}

const translations: Translations = {
  // Onboarding
  'onboarding.step1Desc': { en: "Let's start by choosing how you ride with us.", pt: "Vamos começar escolhendo como você anda conosco." },
  'onboarding.step2Desc': { en: "Create your account to join the community.", pt: "Crie sua conta para se juntar à comunidade." },
  'onboarding.step3Desc': { en: "Tell us a bit about yourself.", pt: "Conte-nos um pouco sobre você." },
  'onboarding.step4RiderDesc': { en: "What's in your garage?", pt: "O que tem na sua garagem?" },
  'onboarding.step4EcosystemDesc': { en: "Tell us about your business.", pt: "Conte-nos sobre o seu negócio." },
  'onboarding.step5RiderDesc': { en: "What are you interested in?", pt: "No que você está interessado?" },
  'onboarding.step5EcosystemDesc': { en: "What services do you offer?", pt: "Quais serviços você oferece?" },
  'onboarding.imRider': { en: "I'm a Rider", pt: "Eu sou um Motociclista" },
  'onboarding.riderDesc': { en: "Join the community, share your rides, find events, and connect with other enthusiasts.", pt: "Junte-se à comunidade, compartilhe seus passeios, encontre eventos e conecte-se com outros entusiastas." },
  'onboarding.imBusiness': { en: "I'm a Business / Club", pt: "Eu sou uma Empresa / Clube" },
  'onboarding.businessDesc': { en: "Create a profile for your cafe, shop, workshop, or motorcycle club to reach riders.", pt: "Crie um perfil para o seu café, loja, oficina ou moto clube para alcançar os motociclistas." },
  'onboarding.usernamePlaceholder': { en: "Choose a unique username", pt: "Escolha um nome de usuário único" },
  'onboarding.emailPlaceholder': { en: "your@email.com", pt: "seu@email.com" },
  'onboarding.fullNamePlaceholder': { en: "Your real name", pt: "Seu nome real" },
  'onboarding.bioPlaceholder': { en: "Tell us a bit about yourself...", pt: "Conte-nos um pouco sobre você..." },
  'onboarding.referralPlaceholder': { en: "Enter code if you have one", pt: "Insira o código se você tiver um" },
  'onboarding.motorcyclePlaceholder': { en: "e.g., Triumph Bonneville T120", pt: "ex: Triumph Bonneville T120" },
  'onboarding.motorcycleHint': { en: "You can add more bikes to your garage later.", pt: "Você pode adicionar mais motos à sua garagem depois." },
  'onboarding.businessNamePlaceholder': { en: "e.g., Ace Cafe London", pt: "ex: Ace Cafe London" },
  'onboarding.businessTypeSelect': { en: "Select a type...", pt: "Selecione um tipo..." },
  'onboarding.back': { en: "Back", pt: "Voltar" },
  'onboarding.complete': { en: "Complete", pt: "Concluir" },
  'onboarding.continue': { en: "Continue", pt: "Continuar" },
  'onboarding.skipForNow': { en: "Skip for now", pt: "Pular por enquanto" },
  'onboarding.welcomeTitle': { en: "Welcome to Café777", pt: "Bem-vindo ao Café777" },
  'onboarding.welcomeSubtitle': { en: "Your profile is ready. Let's ride.", pt: "Seu perfil está pronto. Vamos rodar." },
  'onboarding.errorFields': { en: "Please fill in all required fields.", pt: "Por favor, preencha todos os campos obrigatórios." },
  'onboarding.errorLocation': { en: "Please enter your location.", pt: "Por favor, insira sua localização." },
  'onboarding.errorBusiness': { en: "Please fill in business details.", pt: "Por favor, preencha os detalhes da empresa." },
  'onboarding.errorMotorcycle': { en: "Please enter your motorcycle details.", pt: "Por favor, insira os detalhes da sua motocicleta." },
  'onboarding.errorInterest': { en: "Please select at least one interest.", pt: "Por favor, selecione pelo menos um interesse." },
  'onboarding.errorService': { en: "Please select at least one service.", pt: "Por favor, selecione pelo menos um serviço." },
  'onboarding.successMessage': { en: "Registration successful. Your account is pending approval.", pt: "Registro bem-sucedido. Sua conta está pendente de aprovação." },
  'onboarding.interest.touring': { en: 'Touring & Travel', pt: 'Turismo e Viagens' },
  'onboarding.interest.track': { en: 'Track Days', pt: 'Track Days' },
  'onboarding.interest.custom': { en: 'Custom Builds', pt: 'Customização' },
  'onboarding.interest.photography': { en: 'Photography', pt: 'Fotografia' },
  'onboarding.interest.meetups': { en: 'Local Meetups', pt: 'Encontros Locais' },
  'onboarding.interest.safety': { en: 'Safety & Training', pt: 'Segurança e Treinamento' },
  'onboarding.service.cafe': { en: 'Cafe / Restaurant', pt: 'Café / Restaurante' },
  'onboarding.service.gear': { en: 'Gear & Apparel', pt: 'Equipamentos e Vestuário' },
  'onboarding.service.mechanic': { en: 'Mechanic / Workshop', pt: 'Mecânico / Oficina' },
  'onboarding.service.events': { en: 'Event Organizer', pt: 'Organizador de Eventos' },
  'onboarding.service.tours': { en: 'Guided Tours', pt: 'Passeios Guiados' },
  'onboarding.service.club': { en: 'Motorcycle Club', pt: 'Moto Clube' },

  // FAQ
  'faq.title': { en: 'Help & Support', pt: 'Ajuda e Suporte' },
  'faq.subtitle': { en: 'Frequently Asked Questions', pt: 'Perguntas Frequentes' },
  'faq.emailUs': { en: 'Email Us', pt: 'Envie um E-mail' },
  'faq.instagram': { en: 'Instagram', pt: 'Instagram' },
  'faq.q1': { en: 'How do I record a ride?', pt: 'Como eu gravo um passeio?' },
  'faq.a1': { en: 'To record a ride, go to the Map (Discover) screen, switch to Ride Mode, and tap the "Start Ride" button. Your telemetry and route will be saved automatically when you finish.', pt: 'Para gravar um passeio, vá para a tela do Mapa (Descobrir), mude para o Modo de Pilotagem e toque no botão "Iniciar Passeio". Sua telemetria e rota serão salvas automaticamente quando você terminar.' },
  'faq.q2': { en: 'How do I add a new Pit Stop?', pt: 'Como eu adiciono um novo Pit Stop?' },
  'faq.a2': { en: 'Currently, Pit Stops are curated by our ambassadors and verified users. If you know a great spot, reach out to us on Instagram or via email!', pt: 'Atualmente, os Pit Stops são curados por nossos embaixadores e usuários verificados. Se você conhece um ótimo lugar, entre em contato conosco pelo Instagram ou por e-mail!' },
  'faq.q3': { en: 'What is the Passport feature?', pt: 'O que é o recurso Passaporte?' },
  'faq.a3': { en: 'The Passport allows you to collect digital stamps by visiting legendary motorcycle locations, cafes, and events. It\'s a way to track your adventures and show off your rider cred.', pt: 'O Passaporte permite que você colecione selos digitais visitando locais lendários de motocicletas, cafés e eventos. É uma maneira de acompanhar suas aventuras e mostrar sua credibilidade como motociclista.' },
  'faq.q4': { en: 'How can I join a Motorcycle Club?', pt: 'Como posso me juntar a um Moto Clube?' },
  'faq.a4': { en: 'Navigate to the Community section and select Motorcycle Clubs. You can browse existing clubs and request to join, or start your own if you have a group of riders.', pt: 'Navegue até a seção Comunidade e selecione Moto Clubes. Você pode navegar pelos clubes existentes e solicitar a adesão, ou começar o seu próprio se tiver um grupo de motociclistas.' },

  // Navbar
  'nav.map': { en: 'Map', pt: 'Mapa' },
  'nav.roads': { en: 'Roads', pt: 'Rotas' },
  'nav.events': { en: 'Events', pt: 'Eventos' },
  'nav.myEvents': { en: 'My Events', pt: 'Meus Eventos' },
  'nav.admin': { en: 'Admin', pt: 'Admin' },
  'nav.profile': { en: 'Profile', pt: 'Perfil' },
  'nav.logout': { en: 'Logout', pt: 'Sair' },
  'nav.login': { en: 'Login', pt: 'Entrar' },
  'nav.join': { en: 'Join', pt: 'Cadastrar' },
  'nav.contest': { en: 'Contest', pt: 'Concurso' },
  'nav.notifications': { en: 'Notifications', pt: 'Notificações' },
  'nav.clubs': { en: 'Moto Clubs', pt: 'Moto Clubes' },

  // Home
  'home.hero.title': { en: 'Ride. Connect. Explore.', pt: 'Pilote. Conecte-se. Explore.' },
  'home.hero.subtitle': { en: 'The global platform for the motorcycle community — built on respect, equality, honor, and brotherhood.', pt: 'A plataforma global para a comunidade de motociclistas — construída sobre respeito, igualdade, honra e fraternidade.' },
  'home.hero.cta.join': { en: 'Join the Community', pt: 'Junte-se à Comunidade' },
  'home.hero.cta.explore': { en: 'Explore the Map', pt: 'Explore o Mapa' },
  'home.pillars.riding.title': { en: 'Riding', pt: 'Pilotagem' },
  'home.pillars.riding.desc': { en: 'Freedom, skill, and the pure experience of the open road.', pt: 'Liberdade, habilidade e a pura experiência da estrada aberta.' },
  'home.pillars.community.title': { en: 'Community', pt: 'Comunidade' },
  'home.pillars.community.desc': { en: 'Connection, clubs, and events that bring us together.', pt: 'Conexão, clubes e eventos que nos unem.' },
  'home.pillars.machines.title': { en: 'Machines', pt: 'Máquinas' },
  'home.pillars.machines.desc': { en: 'Customization, maintenance, and the identity of your build.', pt: 'Customização, manutenção e a identidade da sua construção.' },
  'home.pillars.places.title': { en: 'Places', pt: 'Lugares' },
  'home.pillars.places.desc': { en: 'Routes, maps, and the discovery of biker-friendly destinations.', pt: 'Rotas, mapas e a descoberta de destinos amigos dos motociclistas.' },
  'home.code.title': { en: 'Our Code', pt: 'Nosso Código' },
  'home.code.respect.title': { en: 'Respect', pt: 'Respeito' },
  'home.code.respect.desc': { en: 'Earned on the road, given to all who ride.', pt: 'Conquistado na estrada, dado a todos que pilotam.' },
  'home.code.equality.title': { en: 'Equality', pt: 'Igualdade' },
  'home.code.equality.desc': { en: "It doesn't matter what you ride, only that you ride.", pt: 'Não importa o que você pilota, apenas que você pilota.' },
  'home.code.honor.title': { en: 'Honor', pt: 'Honra' },
  'home.code.honor.desc': { en: 'Your word is your bond. Stand by your actions.', pt: 'Sua palavra é seu compromisso. Honre suas ações.' },
  'home.code.brotherhood.title': { en: 'Brotherhood', pt: 'Fraternidade' },
  'home.code.brotherhood.desc': { en: 'Never leave a rider behind. We are one family.', pt: 'Nunca deixe um motociclista para trás. Somos uma família.' },
  'home.ecosystem.title': { en: 'The Ecosystem', pt: 'O Ecossistema' },
  'home.ecosystem.routes.title': { en: 'Discover Routes & Places', pt: 'Descubra Rotas e Lugares' },
  'home.ecosystem.routes.desc': { en: 'Find the best twisties, biker-friendly cafes, and hidden gems on the map.', pt: 'Encontre as melhores curvas, cafés amigos dos motociclistas e joias escondidas no mapa.' },
  'home.ecosystem.connect.title': { en: 'Connect with Riders & Clubs', pt: 'Conecte-se com Motociclistas e Clubes' },
  'home.ecosystem.connect.desc': { en: 'Join local motoclubs, find riding buddies, and build your network.', pt: 'Junte-se a moto clubes locais, encontre parceiros de estrada e construa sua rede.' },
  'home.ecosystem.garage.title': { en: 'Showcase Your Garage', pt: 'Mostre Sua Garagem' },
  'home.ecosystem.garage.desc': { en: 'Display your machines, track mods, and share your build journey.', pt: 'Exiba suas máquinas, acompanhe modificações e compartilhe sua jornada de construção.' },
  'home.ecosystem.events.title': { en: 'Organize & Join Events', pt: 'Organize e Participe de Eventos' },
  'home.ecosystem.events.desc': { en: 'From weekend runs to massive rallies, never miss a ride.', pt: 'De passeios de fim de semana a grandes ralis, nunca perca um passeio.' },
  'home.cta.title': { en: 'This is more than riding. This is a community.', pt: 'Isso é mais do que pilotar. Isso é uma comunidade.' },
  'home.cta.subtitle': { en: 'Leave your mark on the asphalt.', pt: 'Deixe sua marca no asfalto.' },
  'home.cta.btn': { en: 'Start Your Journey', pt: 'Comece Sua Jornada' },
  'home.momentum.title': { en: 'Platform Momentum', pt: 'Momentum da Plataforma' },
  'home.momentum.subtitle': { en: 'Real-time ecosystem growth metrics', pt: 'Métricas de crescimento do ecossistema em tempo real' },
  'home.momentum.riders': { en: 'Active Riders', pt: 'Motociclistas Ativos' },
  'home.momentum.ecosystems': { en: 'Ecosystem Entities', pt: 'Entidades do Ecossistema' },

  // SideMenu
  'menu.rider': { en: 'Rider', pt: 'Motociclista' },
  'menu.viewProfile': { en: 'View Profile', pt: 'Ver Perfil' },
  'menu.loginRegister': { en: 'Login / Register', pt: 'Entrar / Cadastrar' },
  'menu.motorfeed': { en: 'MotorFeed', pt: 'MotorFeed' },
  'menu.discover': { en: 'Discover', pt: 'Descobrir' },
  'menu.mapExplorer': { en: 'Map Explorer', pt: 'Explorador de Mapa' },
  'menu.legendaryRoads': { en: 'Legendary Roads', pt: 'Estradas Lendárias' },
  'menu.photoContest': { en: 'Photo Contest', pt: 'Concurso de Fotos' },
  'menu.community': { en: 'Community', pt: 'Comunidade' },
  'menu.riders': { en: 'Riders', pt: 'Motociclistas' },
  'menu.events': { en: 'Events', pt: 'Eventos' },
  'menu.clubs': { en: 'Motorcycle Clubs', pt: 'Moto Clubes' },
  'menu.applyAmbassador': { en: 'Apply to be an Ambassador', pt: 'Aplicar para ser um Embaixador' },
  'menu.ambassadorDashboard': { en: 'Ambassador Dashboard', pt: 'Painel do Embaixador' },
  'menu.settings': { en: 'Settings', pt: 'Configurações' },
  'menu.notifications': { en: 'Notifications', pt: 'Notificações' },
  'menu.messages': { en: 'Messages', pt: 'Mensagens' },
  'menu.appSettings': { en: 'App Settings', pt: 'Configurações do App' },
  'menu.helpSupport': { en: 'Help & Support', pt: 'Ajuda e Suporte' },
  'menu.logout': { en: 'Logout', pt: 'Sair' },

  // Ambassador
  'ambassador.roleExplanation': { en: 'The Ambassador Network is an infrastructure of trusted locations and community leaders that connect the digital platform with the physical motorcycle world. Ambassadors can be motorcyclists, motoclubs, shops, workshops, cafés, brands, or event organizers.', pt: 'A Rede de Embaixadores é uma infraestrutura de locais de confiança e líderes comunitários que conectam a plataforma digital ao mundo físico das motocicletas. Embaixadores podem ser motociclistas, moto clubes, lojas, oficinas, cafés, marcas ou organizadores de eventos.' },
  'ambassador.notAmbassador': { en: 'You are not currently an ambassador. Apply to become a trusted community node and start issuing passport stamps.', pt: 'Você não é um embaixador atualmente. Aplique para se tornar um nó de confiança da comunidade e comece a emitir selos de passaporte.' },
  'ambassador.applyNow': { en: 'Apply Now', pt: 'Aplicar Agora' },

  // Passport
  'passport.titleMain': { en: 'Biker', pt: 'Passaporte' },
  'passport.titleHighlight': { en: 'Passport', pt: 'Motociclista' },
  'passport.subtitle': { en: 'Your digital legacy on the road', pt: 'Seu legado digital na estrada' },
  'passport.stampsEarned': { en: 'Stamps Earned', pt: 'Selos Coletados' },
  'passport.cat.cities': { en: 'Cities', pt: 'Cidades' },
  'passport.cat.routes': { en: 'Routes', pt: 'Rotas' },
  'passport.cat.events': { en: 'Events', pt: 'Eventos' },
  'passport.cat.ambassadors': { en: 'Ambassadors', pt: 'Embaixadores' },
  'passport.cat.rare': { en: 'Rare', pt: 'Raros' },
  'passport.rarity.common': { en: 'Common', pt: 'Comum' },
  'passport.rarity.rare': { en: 'Rare', pt: 'Raro' },
  'passport.rarity.epic': { en: 'Epic', pt: 'Épico' },
  'passport.issuedBy': { en: 'Issued by', pt: 'Emitido por' },
  'passport.noStamps': { en: 'No stamps collected yet', pt: 'Nenhum selo coletado ainda' },
  'passport.exploreMap': { en: 'Explore the map to find ambassadors and events', pt: 'Explore o mapa para encontrar embaixadores e eventos' },
  'passport.logSubtitle': { en: 'Digital Motorcycle Journey Log', pt: 'Registro Digital de Jornada Motociclista' },
  'passport.totalStamps': { en: 'Total Stamps', pt: 'Total de Selos' },
  'passport.badgesEarned': { en: 'Badges Earned', pt: 'Medalhas Ganhas' },
  'passport.rareItems': { en: 'Rare Items', pt: 'Itens Raros' },
  'passport.travelStamps': { en: 'Travel Stamps', pt: 'Selos de Viagem' },

  // Profile
  'profile.edit': { en: 'Edit Profile', pt: 'Editar Perfil' },
  'profile.demoAccount': { en: 'Demo Account', pt: 'Conta de Demonstração' },
  'profile.yourReferralCode': { en: 'Your Referral Code', pt: 'Seu Código de Indicação' },
  'profile.referralDesc': { en: 'Share this code to earn reputation points.', pt: 'Compartilhe este código para ganhar pontos de reputação.' },
  'profile.connect': { en: 'Connect', pt: 'Conectar' },
  'profile.garage': { en: 'My Garage', pt: 'Minha Garagem' },
  'profile.addMoto': { en: 'Add Motorcycle', pt: 'Adicionar Moto' },
  'profile.noBadgeDescription': { en: 'No description available for this badge.', pt: 'Nenhuma descrição disponível para esta medalha.' },
  'profile.updateMoto': { en: 'Update Motorcycle', pt: 'Atualizar Moto' },
  'profile.cancel': { en: 'Cancel', pt: 'Cancelar' },
  'profile.addLog': { en: 'Add Log', pt: 'Adicionar Registro' },
  'profile.maintenance': { en: 'Maintenance History', pt: 'Histórico de Manutenção' },
  'profile.emptyGarage': { en: 'Empty Garage', pt: 'Garagem Vazia' },
  'profile.noMoto': { en: 'Add your first motorcycle to start tracking maintenance.', pt: 'Adicione sua primeira moto para começar a acompanhar a manutenção.' },
  'profile.myEvents': { en: 'My Events', pt: 'Meus Eventos' },
  'profile.hostedBy': { en: 'Hosted by', pt: 'Organizado por' },
  'profile.me': { en: 'Me', pt: 'Mim' },
  'profile.noEvents': { en: 'No Events', pt: 'Nenhum Evento' },
  'profile.noEventsDesc': { en: 'No events scheduled or attending yet.', pt: 'Nenhum evento agendado ou confirmado ainda.' },
  'profile.aboutUs': { en: 'About Us', pt: 'Sobre Nós' },
  'profile.services': { en: 'Services', pt: 'Serviços' },
  'profile.noDetails': { en: 'No details provided.', pt: 'Nenhum detalhe fornecido.' },
  'profile.updates': { en: 'Feed', pt: 'Feed' },
  'profile.whatsOnMind': { en: "What's on your mind today? Share a ride update or life experience", pt: 'O que você está pensando hoje? Compartilhe uma atualização de passeio ou experiência de vida' },
  'profile.post': { en: 'Post', pt: 'Postar' },
  'profile.posting': { en: 'Posting...', pt: 'Postando...' },
  'profile.noUpdates': { en: 'No updates yet.', pt: 'Nenhuma atualização ainda.' },
  'profile.networkStats': { en: 'Network Stats', pt: 'Estatísticas da Rede' },
  'profile.connections': { en: 'Connections', pt: 'Conexões' },
  'profile.joined': { en: 'Joined', pt: 'Entrou' },
  'profile.contactInfo': { en: 'Contact Info', pt: 'Informações de Contato' },
  'profile.notFound': { en: 'Profile Not Found', pt: 'Perfil Não Encontrado' },
  'profile.notFoundDesc': { en: "The user or business you're looking for doesn't exist.", pt: 'O usuário ou empresa que você está procurando não existe.' },
  'profile.backHome': { en: 'Back to Home', pt: 'Voltar ao Início' },
  'profile.yearsOld': { en: 'years old', pt: 'anos' },
  'profile.make': { en: 'Make', pt: 'Marca' },
  'profile.model': { en: 'Model', pt: 'Modelo' },
  'profile.year': { en: 'Year', pt: 'Ano' },
  'profile.initialLog': { en: 'Initial Maintenance Log', pt: 'Registro de Manutenção Inicial' },
  'profile.service': { en: 'Service (e.g. Oil Change)', pt: 'Serviço (ex. Troca de Óleo)' },
  'profile.shop': { en: 'Shop', pt: 'Oficina' },
  'profile.adding': { en: 'Adding...', pt: 'Adicionando...' },
  'profile.addToGarage': { en: 'Add to Garage', pt: 'Adicionar à Garagem' },
  'profile.saveLog': { en: 'Save Log', pt: 'Salvar Registro' },
  'profile.saving': { en: 'Saving...', pt: 'Salvando...' },
  'profile.attending': { en: 'Attending', pt: 'Confirmado' },
  'profile.description': { en: 'Description', pt: 'Descrição' },
  'profile.updateInfo': { en: 'Update your information for', pt: 'Atualize suas informações para' },
  'profile.save': { en: 'Save Changes', pt: 'Salvar Alterações' },
  'profile.share': { en: 'Share', pt: 'Compartilhar' },
  'profile.recommendations': { en: 'Recommendations', pt: 'Recomendações' },
  'profile.achievements': { en: 'Achievements', pt: 'Conquistas' },

  // Admin
  'admin.title': { en: 'Admin Dashboard', pt: 'Painel de Administração' },
  'admin.subtitle': { en: 'Manage users, access control, and moderation.', pt: 'Gerencie usuários, controle de acesso e moderação.' },
  'admin.tab.users': { en: 'Users', pt: 'Usuários' },
  'admin.tab.events': { en: 'Events', pt: 'Eventos' },
  'admin.tab.submissions': { en: 'Submissions', pt: 'Submissões' },
  'admin.tab.settings': { en: 'Settings', pt: 'Configurações' },
  'admin.tab.badges': { en: 'Badges', pt: 'Medalhas' },
  'admin.tab.contests': { en: 'Contests', pt: 'Concursos' },
  'admin.search.users': { en: 'Search users...', pt: 'Buscar usuários...' },
  'admin.search.events': { en: 'Search events...', pt: 'Buscar eventos...' },
  'admin.table.user': { en: 'User', pt: 'Usuário' },
  'admin.table.type': { en: 'Type', pt: 'Tipo' },
  'admin.table.role': { en: 'Role', pt: 'Função' },
  'admin.table.joined': { en: 'Joined', pt: 'Entrou em' },
  'admin.table.status': { en: 'Status', pt: 'Status' },
  'admin.table.actions': { en: 'Actions', pt: 'Ações' },
  'admin.table.plan': { en: 'Plan', pt: 'Plano' },
  'admin.table.event': { en: 'Event', pt: 'Evento' },
  'admin.table.host': { en: 'Host', pt: 'Organizador' },
  'admin.table.date': { en: 'Date', pt: 'Data' },
  'admin.table.promoted': { en: 'Promoted', pt: 'Promovido' },
  'admin.table.photo': { en: 'Photo', pt: 'Foto' },
  'admin.table.contest': { en: 'Contest', pt: 'Concurso' },
  'admin.noUsers': { en: 'No users found', pt: 'Nenhum usuário encontrado' },
  'admin.noEvents': { en: 'No events found', pt: 'Nenhum evento encontrado' },
  'admin.settings.title': { en: 'Platform Settings', pt: 'Configurações da Plataforma' },
  'admin.settings.interface': { en: 'Interface Features', pt: 'Recursos de Interface' },
  'admin.settings.fullscreen': { en: 'Enable Fullscreen Feature', pt: 'Ativar Recurso de Tela Cheia' },
  'admin.settings.fullscreenDesc': { en: 'Adds a fullscreen toggle to the navigation bar', pt: 'Adiciona um botão de tela cheia na barra de navegação' },
  'admin.settings.registration': { en: 'Registration Policy', pt: 'Política de Registro' },
  'admin.settings.approval': { en: 'Require approval for Ecosystems', pt: 'Exigir aprovação para Ecossistemas' },
  'admin.settings.allowRiders': { en: 'Allow new Rider registrations', pt: 'Permitir novos registros de Motociclistas' },
  'admin.settings.moderation': { en: 'Content Moderation', pt: 'Moderação de Conteúdo' },
  'admin.settings.autoHide': { en: 'Auto-hide reported posts', pt: 'Ocultar automaticamente posts denunciados' },
  'admin.settings.aiFilter': { en: 'Enable AI image filtering', pt: 'Ativar filtragem de imagem por IA' },
  'admin.settings.save': { en: 'Save Changes', pt: 'Salvar Alterações' },
  'admin.featureAccess.title': { en: 'Feature Access Control', pt: 'Controle de Acesso a Recursos' },
  'admin.featureAccess.allowedPlan': { en: 'Minimum Plan Required', pt: 'Plano Mínimo Exigido' },
  'admin.notification.planUpdated': { en: 'User plan updated successfully', pt: 'Plano do usuário atualizado com sucesso' },
  'admin.notification.settingsUpdated': { en: 'Settings updated successfully', pt: 'Configurações atualizadas com sucesso' },
  'admin.notification.error': { en: 'An error occurred', pt: 'Ocorreu um erro' },
  'admin.notification.badgeAwarded': { en: 'Badge awarded successfully', pt: 'Medalha concedida com sucesso' },
  'admin.notification.badgeFailed': { en: 'Failed to award badge', pt: 'Falha ao conceder medalha' },
  'admin.notification.winnerPicked': { en: 'Winner picked successfully', pt: 'Vencedor escolhido com sucesso' },
  'admin.notification.emailUpdated': { en: 'User email updated successfully', pt: 'E-mail do usuário atualizado com sucesso' },
  'admin.confirm.deleteContest': { en: 'Are you sure you want to delete this contest?', pt: 'Tem certeza de que deseja excluir este concurso?' },
  'admin.confirm.deleteUser': { en: 'Are you sure you want to delete this user?', pt: 'Tem certeza de que deseja excluir este usuário?' },
  'admin.confirm.pickWinner': { en: "Are you sure you want to pick a winner now? This will end the contest early if it hasn't ended yet.", pt: 'Tem certeza de que deseja escolher um vencedor agora? Isso encerrará o concurso antecipadamente se ainda não tiver terminado.' },
  'admin.accessDenied': { en: 'Access Denied', pt: 'Acesso Negado' },
  'admin.noPermission': { en: 'You do not have permission to view this page.', pt: 'Você não tem permissão para ver esta página.' },
  'admin.goToLogin': { en: 'Go to Admin Login', pt: 'Ir para Login de Admin' },
  'admin.status.active': { en: 'Active', pt: 'Ativo' },
  'admin.status.pending': { en: 'Pending', pt: 'Pendente' },
  'admin.status.banned': { en: 'Banned', pt: 'Banido' },
  'admin.status.approved': { en: 'Approved', pt: 'Aprovado' },
  'admin.status.promoted': { en: 'Promoted', pt: 'Promovido' },
  'admin.status.standard': { en: 'Standard', pt: 'Padrão' },
  'admin.action.approve': { en: 'Approve', pt: 'Aprovar' },
  'admin.action.edit': { en: 'Edit', pt: 'Editar' },
  'admin.action.ban': { en: 'Ban', pt: 'Banir' },
  'admin.action.delete': { en: 'Delete', pt: 'Excluir' },
  'admin.action.promote': { en: 'Promote', pt: 'Promover' },
  'admin.action.unpromote': { en: 'Unpromote', pt: 'Despromover' },
  'admin.action.reject': { en: 'Reject', pt: 'Rejeitar' },
  'admin.action.unapprove': { en: 'Unapprove', pt: 'Desaprovar' },
  'admin.action.award': { en: 'Award', pt: 'Premiar' },
  'admin.role.user': { en: 'User', pt: 'Usuário' },
  'admin.role.moderator': { en: 'Moderator', pt: 'Moderador' },
  'admin.role.admin': { en: 'Admin', pt: 'Admin' },
  'admin.plan.freemium': { en: 'Freemium', pt: 'Freemium' },
  'admin.plan.premium': { en: 'Premium', pt: 'Premium' },
  'admin.action.submit': { en: 'Submit', pt: 'Enviar' },
  'admin.action.editEmail': { en: 'Edit Email', pt: 'Editar E-mail' },
  'admin.editEmail.title': { en: 'Edit User Email', pt: 'Editar E-mail do Usuário' },
  'admin.editEmail.label': { en: 'New Email Address', pt: 'Novo Endereço de E-mail' },
  'admin.editEmail.submit': { en: 'Update Email', pt: 'Atualizar E-mail' },
  'admin.badges.create': { en: 'Create New Badge', pt: 'Criar Nova Medalha' },
  'admin.badges.name': { en: 'Badge Name', pt: 'Nome da Medalha' },
  'admin.badges.description': { en: 'Badge Description', pt: 'Descrição da Medalha' },
  'admin.badges.icon': { en: 'Icon (Lucide name)', pt: 'Ícone (nome Lucide)' },
  'admin.badges.color': { en: 'Color (Hex)', pt: 'Cor (Hex)' },
  'admin.badges.submit': { en: 'Create Badge', pt: 'Criar Medalha' },
  'admin.badges.awardTitle': { en: 'Award Badge', pt: 'Premiar com Medalha' },
  'admin.badges.selectUser': { en: 'Select User', pt: 'Selecionar Usuário' },
  'admin.badges.selectBadge': { en: 'Select Badge', pt: 'Selecionar Medalha' },
  'admin.contests.create': { en: 'Create New Contest', pt: 'Criar Novo Concurso' },
  'admin.contests.title': { en: 'Contest Title', pt: 'Título do Concurso' },
  'admin.contests.description': { en: 'Contest Description', pt: 'Descrição do Concurso' },
  'admin.contests.startDate': { en: 'Start Date', pt: 'Data de Início' },
  'admin.contests.votingStartDate': { en: 'Voting Start Date (Optional)', pt: 'Data de Início da Votação (Opcional)' },
  'admin.contests.endDate': { en: 'End Date', pt: 'Data de Término' },
  'admin.contests.submit': { en: 'Create Contest', pt: 'Criar Concurso' },
  'admin.contests.entryPhoto': { en: 'Photo URL', pt: 'URL da Foto' },
  'admin.contests.entrySubmit': { en: 'Submit Entry', pt: 'Enviar Entrada' },
  'admin.submissions.title': { en: 'Submissions Moderation', pt: 'Moderação de Submissões' },
  'admin.eventPhotos.title': { en: 'Event Photos', pt: 'Fotos de Eventos' },
  'admin.submissions.filterContest': { en: 'Filter by Contest:', pt: 'Filtrar por Concurso:' },
  'admin.submissions.allContests': { en: 'All Contests', pt: 'Todos os Concursos' },
  'admin.submissions.votes': { en: 'Votes', pt: 'Votos' },
  'admin.contests.pageTitle': { en: 'Photo Contests', pt: 'Concursos de Fotos' },
  'admin.contests.edit': { en: 'Edit Contest', pt: 'Editar Concurso' },
  'admin.contests.status.draft': { en: 'Draft', pt: 'Rascunho' },
  'admin.contests.status.active': { en: 'Active', pt: 'Ativo' },
  'admin.contests.status.completed': { en: 'Completed', pt: 'Concluído' },
  'admin.contests.prize': { en: 'Prize Description', pt: 'Descrição do Prêmio' },
  'admin.contests.prizeBadge': { en: 'Prize Badge (Optional)', pt: 'Medalha do Prêmio (Opcional)' },
  'admin.contests.prizeLabel': { en: 'Prize:', pt: 'Prêmio:' },
  'admin.contests.selectBadge': { en: 'Select Badge', pt: 'Selecionar Medalha' },
  'admin.contests.searchBadges': { en: 'Search badges...', pt: 'Buscar medalhas...' },
  'admin.contests.none': { en: 'None', pt: 'Nenhum' },
  'admin.contests.prizePlaceholder': { en: 'e.g. Special Badge + 500 Reputation Points', pt: 'ex: Medalha Especial + 500 Pontos de Reputação' },
  'admin.contests.update': { en: 'Update Contest', pt: 'Atualizar Concurso' },
  'admin.contests.dates': { en: 'Dates', pt: 'Datas' },
  'admin.contests.leaderWinner': { en: 'Leader/Winner', pt: 'Líder/Vencedor' },
  'admin.contests.winner': { en: 'Winner: @{username}', pt: 'Vencedor: @{username}' },
  'admin.contests.leader': { en: 'Leader: @{username} ({votes}v)', pt: 'Líder: @{username} ({votes}v)' },
  'admin.contests.noEntries': { en: 'No entries yet', pt: 'Nenhuma entrada ainda' },
  'admin.contests.pickWinner': { en: 'Pick Winner', pt: 'Escolher Vencedor' },
  'admin.contests.noContests': { en: 'No contests found', pt: 'Nenhum concurso encontrado' },
  'admin.badges.pageTitle': { en: 'Badges', pt: 'Medalhas' },
  'admin.badges.category': { en: 'Category', pt: 'Categoria' },
  'admin.badges.descriptionOptional': { en: 'Description (Optional)', pt: 'Descrição (Opcional)' },
  'admin.badges.image': { en: 'Badge Image', pt: 'Imagem da Medalha' },
  'admin.badges.upload': { en: 'Upload Image', pt: 'Carregar Imagem' },
  'admin.badges.uploading': { en: 'Uploading...', pt: 'Carregando...' },
  'admin.badges.creatorType': { en: 'Creator Type', pt: 'Tipo de Criador' },
  'admin.badges.creator.platform': { en: 'Platform', pt: 'Plataforma' },
  'admin.badges.creator.business': { en: 'Ecosystem Shop', pt: 'Loja do Ecossistema' },
  'admin.badges.creator.event': { en: 'Event', pt: 'Evento' },
  'admin.badges.creator.club': { en: 'Club', pt: 'Clube' },
  'admin.badges.assignShop': { en: 'Assign Shop', pt: 'Atribuir Loja' },
  'admin.badges.searchShop': { en: 'Search Shop Name...', pt: 'Buscar Nome da Loja...' },
  'admin.badges.award.search': { en: 'Search User or Shop', pt: 'Buscar Usuário ou Loja' },
  'admin.badges.award.searchPlaceholder': { en: 'Search by name or username...', pt: 'Buscar por nome ou usuário...' },
  'admin.badges.award.confirm': { en: 'Confirm Award', pt: 'Confirmar Premiação' },
  'admin.settings.flags': { en: 'Feature Flags', pt: 'Sinalizadores de Recursos' },

  // MotorFeed
  'feed.title.motor': { en: 'Motor', pt: 'Motor' },
  'feed.title.feed': { en: 'Feed', pt: 'Feed' },
  'feed.search': { en: 'Search', pt: 'Buscar' },
  'feed.filter': { en: 'Filter', pt: 'Filtrar' },
  'feed.category.all': { en: 'All', pt: 'Tudo' },
  'feed.category.routes': { en: 'Routes', pt: 'Rotas' },
  'feed.category.events': { en: 'Events', pt: 'Eventos' },
  'feed.category.clubs': { en: 'Clubs', pt: 'Clubes' },
  'feed.category.bikes': { en: 'Bikes', pt: 'Motos' },
  'feed.create.placeholder': { en: "What's on your mind, {name}?", pt: 'O que você está pensando, {name}?' },
  'feed.create.button': { en: 'Post to MotorFeed', pt: 'Postar no MotorFeed' },
  'feed.create.posting': { en: 'Posting...', pt: 'Postando...' },
  'feed.create.title': { en: 'Create Post', pt: 'Criar Post' },
  'feed.create.textarea': { en: 'Share your latest ride or thoughts...', pt: 'Compartilhe sua última viagem ou pensamentos...' },
  'feed.create.addPhoto': { en: 'Add Photo', pt: 'Adicionar Foto' },
  'feed.create.changePhoto': { en: 'Change Photo', pt: 'Alterar Foto' },
  'feed.create.tagMotorcycle': { en: 'Tag Motorcycle', pt: 'Marcar Moto' },
  'feed.post.pinned': { en: 'Pinned', pt: 'Fixado' },
  'feed.post.respect': { en: 'Respect', pt: 'Respeito' },
  'feed.post.unpin': { en: 'Unpin', pt: 'Desafixar' },
  'feed.post.pin': { en: 'Pin', pt: 'Fixar' },
  'feed.post.noPosts': { en: 'No posts found', pt: 'Nenhum post encontrado' },
  'feed.post.success': { en: 'Post created successfully!', pt: 'Post criado com sucesso!' },
  'feed.post.error': { en: 'Failed to create post', pt: 'Falha ao criar post' },
  'feed.post.errorGeneric': { en: 'An error occurred while creating post', pt: 'Ocorreu um erro ao criar o post' },
  'feed.post.pinnedSuccess': { en: 'Post pinned to top!', pt: 'Post fixado no topo!' },
  'feed.post.unpinnedSuccess': { en: 'Post unpinned', pt: 'Post desafixado' },
  'feed.post.pinError': { en: 'Failed to pin post', pt: 'Falha ao fixar post' },
  'feed.post.pinErrorGeneric': { en: 'An error occurred while pinning post', pt: 'Ocorreu um erro ao fixar o post' },
  'feed.fetchError': { en: 'Failed to fetch posts', pt: 'Falha ao buscar posts' },
  'feed.post.comments': { en: 'Comments', pt: 'Comentários' },
  'feed.writeComment': { en: 'Write a comment...', pt: 'Escreva um comentário...' },
  'feed.noComments': { en: 'No comments yet. Be the first to comment!', pt: 'Nenhum comentário ainda. Seja o primeiro a comentar!' },
  'feed.commentSuccess': { en: 'Comment added!', pt: 'Comentário adicionado!' },
  'feed.commentError': { en: 'Failed to add comment', pt: 'Falha ao adicionar comentário' },
  'feed.commentErrorGeneric': { en: 'An error occurred while adding comment', pt: 'Ocorreu um erro ao adicionar o comentário' },
  'feed.mentions': { en: 'Mentions', pt: 'Menções' },

  // Map
  'map.title': { en: 'Ecosystem Map', pt: 'Mapa do Ecossistema' },
  'map.subtitle': { en: 'Discover repair shops, dealerships, and biker-friendly spots around you.', pt: 'Descubra oficinas, concessionárias e locais amigos dos motociclistas perto de você.' },
  'map.legend': { en: 'Legend', pt: 'Legenda' },
  'map.viewProfile': { en: 'View Profile', pt: 'Ver Perfil' },

  // Discover
  'discover.pitstop': { en: 'Pit Stop', pt: 'Pit Stop' },
  'discover.ride': { en: 'Ride', pt: 'Pilotar' },
  'discover.locationsNearby': { en: 'Locations Nearby', pt: 'Locais Próximos' },
  'discover.focus': { en: 'Focus', pt: 'Focar' },
  'discover.directions': { en: 'Directions', pt: 'Direções' },
  'discover.startRide': { en: 'Start Ride', pt: 'Iniciar Passeio' },
  'discover.smart.suggested': { en: 'Rest Stop Suggested', pt: 'Sugestão de Parada' },
  'discover.smart.desc': { en: 'BH Riders Café is 5 miles ahead.', pt: 'BH Riders Café está a 8 km à frente.' },
  'discover.import.success': { en: 'Successfully imported {count} route(s).', pt: 'Sucesso ao importar {count} rota(s).' },
  'discover.import.error': { en: 'Failed to parse one or more GPX files. Please ensure they are valid formats.', pt: 'Falha ao analisar um ou mais arquivos GPX. Verifique se os formatos são válidos.' },
  'discover.import.sizeError': { en: 'File {name} exceeds 10MB limit.', pt: 'O arquivo {name} excede o limite de 10MB.' },
  'discover.searchArea': { en: 'Search this area', pt: 'Buscar nesta área' },
  'discover.searchSuccess': { en: 'Found {count} places', pt: 'Encontrado {count} locais' },
  'discover.searchError': { en: 'Failed to fetch nearby places', pt: 'Falha ao buscar locais próximos' },
  'discover.searchAlongRoute': { en: 'Search Along Route', pt: 'Buscar na Rota' },
  'discover.viewProfile': { en: 'View Profile', pt: 'Ver Perfil' },
  'discover.suggestEcosystem': { en: 'Suggest as Ecosystem', pt: 'Sugerir como Ecossistema' },
  'discover.suggestComingSoon': { en: 'Suggest feature coming soon!', pt: 'Recurso de sugestão em breve!' },
  'discover.uploadGPX': { en: 'Upload GPX', pt: 'Carregar GPX' },
  'discover.mock.motoCity': { en: 'Largest motorcycle hub in the city.', pt: 'O maior hub de motocicletas da cidade.' },
  'discover.mock.valence': { en: 'Authorized Yamaha dealer and service center.', pt: 'Concessionária autorizada Yamaha e centro de serviços.' },
  'discover.mock.savassi': { en: 'Popular gathering spot for riders in the heart of Savassi.', pt: 'Ponto de encontro popular para motociclistas no coração da Savassi.' },
  'discover.mock.cafe': { en: 'Specialty coffee and a great atmosphere for bikers.', pt: 'Café especial e uma ótima atmosfera para motociclistas.' },
  'discover.mock.ironRiders': { en: 'Traditional motorcycle club headquarters.', pt: 'Sede de moto clube tradicional.' },
  'discover.mock.estradaReal': { en: 'Historical stop along the legendary Estrada Real.', pt: 'Parada histórica ao longo da lendária Estrada Real.' },
  'discover.mock.passport': { en: 'Scan here to collect your first digital stamp!', pt: 'Escaneie aqui para coletar seu primeiro selo digital!' },
  'discover.mock.ambassador': { en: 'Meet our local ambassador and learn about the community.', pt: 'Conheça nosso embaixador local e saiba mais sobre a comunidade.' },
  'discover.mock.rolaMoca': { en: 'Breathtaking views and perfect curves for riding.', pt: 'Vistas de tirar o fôlego e curvas perfeitas para pilotar.' },
  'discover.mock.estradaRealRoute': { en: 'Historical route connecting Ouro Preto to the coast.', pt: 'Rota histórica ligando Ouro Preto ao litoral.' },
  'partsAndService.title': { en: 'Parts & Service', pt: 'Peças e Serviços' },
  'partsAndService.subtitle': { en: 'Find dealerships, repair shops, and parts stores near you.', pt: 'Encontre concessionárias, oficinas e lojas de peças perto de você.' },
  'partsAndService.keywordsPlaceholder': { en: 'Keywords (e.g., oil change, Yamaha, tires)', pt: 'Palavras-chave (ex: troca de óleo, Yamaha, pneus)' },
  'partsAndService.locationPlaceholder': { en: 'Location (e.g., Los Angeles, CA)', pt: 'Localização (ex: São Paulo, SP)' },
  'partsAndService.search': { en: 'Search', pt: 'Buscar' },
  'partsAndService.noResults': { en: 'No results found', pt: 'Nenhum resultado encontrado' },
  'partsAndService.tryAdjusting': { en: 'Try adjusting your keywords or location.', pt: 'Tente ajustar suas palavras-chave ou localização.' },
  'partsAndService.viewProfile': { en: 'View Profile', pt: 'Ver Perfil' },
  'partsAndService.viewOnMap': { en: 'View on Map', pt: 'Ver no Mapa' },
  'partsAndService.category.repair': { en: 'Repair Shop', pt: 'Oficina' },
  'partsAndService.category.dealership': { en: 'Dealership', pt: 'Concessionária' },
  'partsAndService.category.parts': { en: 'Parts Store', pt: 'Loja de Peças' },
  'partsAndService.category.parts_store': { en: 'Parts Store', pt: 'Loja de Peças' },
  'partsAndService.category.other': { en: 'Other', pt: 'Outro' },
  'discover.groups.ecosystems': { en: 'Ecosystems', pt: 'Ecossistemas' },
  'discover.groups.businesses': { en: 'Businesses', pt: 'Negócios' },
  'discover.groups.hangouts': { en: 'Hangouts', pt: 'Pontos de Encontro' },
  'discover.groups.community': { en: 'Community', pt: 'Comunidade' },
  'discover.groups.events': { en: 'Events', pt: 'Eventos' },
  'discover.groups.routes': { en: 'Routes', pt: 'Rotas' },
  'discover.groups.spots': { en: 'Spots', pt: 'Pontos' },

  // Roads Discovery
  'roads.title': { en: 'Discovery Engine', pt: 'Motor de Descoberta' },
  'roads.subtitle': { en: 'AI-Powered Route Analysis', pt: 'Análise de Rotas por IA' },
  'roads.search': { en: 'Search regions, tags...', pt: 'Buscar regiões, tags...' },
  'roads.filter.all': { en: 'All Routes', pt: 'Todas as Rotas' },
  'roads.filter.twisty': { en: 'Twisty', pt: 'Sinuosas' },
  'roads.filter.scenic': { en: 'Scenic', pt: 'Cênicas' },
  'roads.filter.legendary': { en: 'Legendary', pt: 'Lendárias' },
  'roads.filter.hidden': { en: 'Hidden Gems', pt: 'Joias Escondidas' },
  'roads.score': { en: 'Road Score', pt: 'Pontuação da Rota' },
  'roads.metrics.curvature': { en: 'Curvature', pt: 'Curvatura' },
  'roads.metrics.elevation': { en: 'Elevation', pt: 'Elevação' },
  'roads.metrics.scenic': { en: 'Scenic', pt: 'Cênico' },
  'roads.metrics.stops': { en: 'Stops', pt: 'Paradas' },
  'roads.metrics.popular': { en: 'Popular', pt: 'Popular' },
  'roads.btn.ride': { en: 'Ride This Route', pt: 'Pilotar Esta Rota' },
  'roads.btn.details': { en: 'View Details', pt: 'Ver Detalhes' },
  'roads.import.btn': { en: 'Import GPX', pt: 'Importar GPX' },
  'roads.aiScore': { en: 'AI Score', pt: 'Pontuação IA' },
  'roads.analyzed': { en: 'Analyzed', pt: 'Analisado' },
  'roads.poi.ecosystem': { en: 'Ecosystem', pt: 'Ecossistema' },
  'roads.poi.distance': { en: 'km from route', pt: 'km da rota' },
  'roads.poi.profile': { en: 'Profile', pt: 'Perfil' },
  'roads.poi.navigate': { en: 'Navigate', pt: 'Navegar' },

  // Categories
  'category.dealership': { en: 'Dealership', pt: 'Concessionária' },
  'category.gear_shop': { en: 'Gear Shop', pt: 'Loja de Equipamentos' },
  'category.parts_store': { en: 'Parts Store', pt: 'Loja de Peças' },
  'category.workshop': { en: 'Workshop', pt: 'Oficina' },
  'category.meeting_spot': { en: 'Meeting Spot', pt: 'Ponto de Encontro' },
  'category.ride_spot': { en: 'Ride Spot', pt: 'Ponto de Passeio' },
  'category.biker_cafe': { en: 'Biker Cafe', pt: 'Café Motociclista' },
  'category.biker_bar': { en: 'Biker Bar', pt: 'Bar Motociclista' },
  'category.ride_stop': { en: 'Ride Stop', pt: 'Parada de Passeio' },
  'category.motoclub': { en: 'Moto Club', pt: 'Moto Clube' },
  'category.ride_route': { en: 'Ride Route', pt: 'Rota de Passeio' },
  'category.repair': { en: 'Repair Shop', pt: 'Oficina de Reparos' },
  'category.parts': { en: 'Parts Store', pt: 'Loja de Peças' },
  'category.club': { en: 'Motorcycle Club', pt: 'Moto Clube' },
  'category.barbershop': { en: 'Barbershop', pt: 'Barbearia' },
  'category.band': { en: 'Band / Entertainment', pt: 'Banda / Entretenimento' },
  'category.other': { en: 'Other', pt: 'Outro' },
  'category.passport_stamp': { en: 'Passport Stamp', pt: 'Selo do Passaporte' },
  'category.ambassador': { en: 'Ambassador', pt: 'Embaixador' },
  'category.gas_station': { en: 'Gas Station', pt: 'Posto de Gasolina' },
  'category.parking': { en: 'Parking', pt: 'Estacionamento' },
  'category.viewpoint': { en: 'Viewpoint', pt: 'Mirante' },
  'category.mountain_pass': { en: 'Mountain Pass', pt: 'Passo de Montanha' },
  'category.rest_stop': { en: 'Rest Stop', pt: 'Parada de Descanso' },

  // Events
  'events.title': { en: 'Upcoming Events', pt: 'Próximos Eventos' },
  'events.subtitle': { en: 'Rides, meetups, and showcases in your area.', pt: 'Passeios, encontros e exposições na sua área.' },
  'events.filter.title': { en: 'Filter by title...', pt: 'Filtrar por título...' },
  'events.filter.location': { en: 'Filter by location...', pt: 'Filtrar por local...' },
  'events.create': { en: 'Create Event', pt: 'Criar Evento' },
  'events.promoted': { en: 'Promoted', pt: 'Promovido' },
  'events.category.all': { en: 'All Categories', pt: 'Todas as Categorias' },
  'events.category.road_trip': { en: 'Road Trip', pt: 'Viagem de Estrada' },
  'events.category.club_meetup': { en: 'Club Meetup', pt: 'Encontro de Clube' },
  'events.category.shop_event': { en: 'Shop Event', pt: 'Evento de Loja' },
  'events.category.track_day': { en: 'Track Day', pt: 'Track Day' },
  'events.category.other': { en: 'Other', pt: 'Outro' },
  'events.view.list': { en: 'List View', pt: 'Visualização em Lista' },
  'events.view.grid': { en: 'Grid View', pt: 'Visualização em Grade' },
  'event.field.category': { en: 'Category', pt: 'Categoria' },
  'events.attending': { en: 'Attending', pt: 'Confirmado' },
  'events.rsvp': { en: 'RSVP', pt: 'Confirmar' },
  'events.loginToRSVP': { en: 'Please login to RSVP', pt: 'Por favor, faça login para confirmar' },
  'events.searchPlaceholder': { en: 'Search by title or location...', pt: 'Buscar por título ou local...' },
  'events.noFound': { en: 'No Events Found', pt: 'Nenhum Evento Encontrado' },
  'events.checkBack': { en: 'Check back later for upcoming rides and meetups.', pt: 'Volte mais tarde para novos passeios e encontros.' },
  'events.submitPhoto': { en: 'Submit Photo', pt: 'Enviar Foto' },
  'events.vote': { en: 'Vote', pt: 'Votar' },
  'events.unpromote': { en: 'Unpromote', pt: 'Remover Promoção' },
  'events.promote': { en: 'Promote', pt: 'Promover' },
  'events.noHosted': { en: 'No hosted events yet', pt: 'Nenhum evento criado ainda' },
  'events.notAttending': { en: 'Not attending any events yet', pt: 'Não está participando de nenhum evento ainda' },

  // Create Event Modal
  'event.modal.title': { en: 'Create New Event', pt: 'Criar Novo Evento' },
  'event.modal.editTitle': { en: 'Edit Event', pt: 'Editar Evento' },
  'event.modal.subtitle': { en: 'Share your next ride or meetup with the community.', pt: 'Compartilhe seu próximo passeio ou encontro com a comunidade.' },
  'event.modal.titlePlaceholder': { en: 'e.g. Sunday Morning Canyon Run', pt: 'ex: Passeio de Domingo de Manhã' },
  'event.modal.timePlaceholder': { en: 'e.g. 08:00 AM', pt: 'ex: 08:00' },
  'event.modal.locationPlaceholder': { en: 'e.g. Mulholland Hwy, Malibu', pt: 'ex: Av. Paulista, São Paulo' },
  'event.modal.descPlaceholder': { en: "What's the plan? Route details, skill level, etc.", pt: 'Qual o plano? Detalhes da rota, nível de habilidade, etc.' },
  'event.details.loginToUpload': { en: 'Please login to upload photos', pt: 'Por favor, faça login para enviar fotos' },
  'event.details.uploadSuccess': { en: 'Photo uploaded for approval', pt: 'Foto enviada para aprovação' },
  'event.details.dropPhotos': { en: 'Drop photos here', pt: 'Solte as fotos aqui' },
  'event.details.orClickToBrowse': { en: 'or click to browse', pt: 'ou clique para procurar' },
  'event.details.uploading': { en: 'Uploading...', pt: 'Enviando...' },
  'event.details.uploadFailed': { en: 'Failed to upload photos', pt: 'Falha ao enviar fotos' },
  'event.details.promoteToContest': { en: 'Promote to Contest', pt: 'Promover para Concurso' },
  'admin.contestPromotion.title': { en: 'Contest Promotion Settings', pt: 'Configurações de Promoção de Concurso' },
  'admin.contestPromotion.enable': { en: 'Enable Photo Contest', pt: 'Habilitar Concurso de Fotos' },
  'admin.contestPromotion.allowedTypes': { en: 'Allowed Account Types', pt: 'Tipos de Conta Permitidos' },
  'admin.contestPromotion.freemium': { en: 'Freemium', pt: 'Freemium' },
  'admin.contestPromotion.premium': { en: 'Premium', pt: 'Premium' },
  'event.details.communityEvent': { en: 'Community Event', pt: 'Evento da Comunidade' },
  'event.details.showTicket': { en: 'Show Ticket', pt: 'Ver Ingresso' },
  'event.details.manageAttendance': { en: 'Manage Attendance', pt: 'Gerenciar Participantes' },
  'event.details.editEvent': { en: 'Edit Event', pt: 'Editar Evento' },
  'event.details.gallery': { en: 'Event Gallery', pt: 'Galeria do Evento' },
  'event.details.uploadPhoto': { en: 'Upload Photo', pt: 'Enviar Foto' },
  'event.details.pending': { en: 'Pending', pt: 'Pendente' },
  'event.details.pendingApproval': { en: 'Pending Approval', pt: 'Aguardando Aprovação' },
  'event.details.approve': { en: 'Approve', pt: 'Aprovar' },
  'event.details.reject': { en: 'Reject', pt: 'Rejeitar' },
  'event.details.approveAll': { en: 'Approve All', pt: 'Aprovar Todos' },
  'event.details.rejectAll': { en: 'Reject All', pt: 'Rejeitar Todos' },
  'event.details.noPendingPhotos': { en: 'No pending photos.', pt: 'Nenhuma foto aguardando aprovação.' },
  'event.details.photosApproved': { en: 'Photos approved successfully!', pt: 'Fotos aprovadas com sucesso!' },
  'event.details.photosRejected': { en: 'Photos rejected successfully!', pt: 'Fotos rejeitadas com sucesso!' },
  'event.field.coverImage': { en: 'Cover Image', pt: 'Imagem de Capa' },
  'event.field.uploadCover': { en: 'Upload Cover', pt: 'Upload de Capa' },
  'event.upload.coverDesc': { en: 'Choose a high-quality image to represent your event.', pt: 'Escolha uma imagem de alta qualidade para representar seu evento.' },
  'event.field.title': { en: 'Event Title', pt: 'Título do Evento' },
  'event.field.date': { en: 'Date', pt: 'Data' },
  'event.field.time': { en: 'Time', pt: 'Hora' },
  'event.field.location': { en: 'Location', pt: 'Local' },
  'event.field.image': { en: 'Event Image', pt: 'Imagem do Evento' },
  'event.field.participationBadge': { en: 'Participation Badge (Prize)', pt: 'Medalha de Participação (Prêmio)' },
  'event.field.participationStamp': { en: 'Participation Stamp', pt: 'Selo do Passaporte' },
  'event.field.upload': { en: 'Upload', pt: 'Enviar' },
  'event.field.remove': { en: 'Remove Image', pt: 'Remover Imagem' },
  'event.field.description': { en: 'Description', pt: 'Descrição' },
  'event.modal.noBadgeSelected': { en: 'No badge selected', pt: 'Nenhuma medalha selecionada' },
  'event.modal.noBadge': { en: 'No Badge', pt: 'Sem Medalha' },
  'event.btn.publish': { en: 'Publish Event', pt: 'Publicar Evento' },
  'event.btn.update': { en: 'Update Event', pt: 'Atualizar Evento' },
  'event.btn.creating': { en: 'Creating...', pt: 'Criando...' },
  'event.btn.updating': { en: 'Updating...', pt: 'Atualizando...' },
  'event.preview.noImage': { en: 'No image selected', pt: 'Nenhuma imagem selecionada' },
  'event.preview.title': { en: 'Preview', pt: 'Pré-visualização' },
  'event.upload.desc': { en: 'Upload a cover image for your event. Recommended size: 1200x600px.', pt: 'Envie uma imagem de capa para o seu evento. Tamanho recomendado: 1200x600px.' },

  // Event Details
  'eventDetails.back': { en: 'Back to Events', pt: 'Voltar para Eventos' },
  'eventDetails.date': { en: 'Date', pt: 'Data' },
  'eventDetails.time': { en: 'Time', pt: 'Hora' },
  'eventDetails.location': { en: 'Location', pt: 'Local' },
  'eventDetails.attendance': { en: 'Attendance', pt: 'Participantes' },
  'eventDetails.riders': { en: 'Riders', pt: 'Motociclistas' },
  'eventDetails.participationBadge': { en: 'Participation Badge', pt: 'Medalha de Participação' },
  'eventDetails.about': { en: 'About this event', pt: 'Sobre este evento' },
  'eventDetails.hostedBy': { en: 'Hosted by', pt: 'Organizado por' },
  'event.details.posted': { en: 'Posted', pt: 'Postado em' },
  'event.details.attendance': { en: 'Attendance', pt: 'Participantes' },
  'event.details.ridersAttending': { en: 'Riders Attending', pt: 'Motociclistas Confirmados' },
  'event.details.participationBadge': { en: 'Participation Badge', pt: 'Medalha de Participação' },
  'event.details.rsvpNow': { en: 'RSVP Now', pt: 'Confirmar Agora' },
  'event.details.imAttending': { en: 'I\'m Attending', pt: 'Eu Vou' },
  'event.details.share': { en: 'Share Event', pt: 'Compartilhar Evento' },
  'event.details.about': { en: 'About this event', pt: 'Sobre este evento' },
  'event.details.hostedBy': { en: 'Hosted by', pt: 'Organizado por' },
  'event.details.viewProfile': { en: 'View Profile', pt: 'Ver Perfil' },
  'event.share.title': { en: 'Share Event', pt: 'Compartilhar Evento' },
  'event.share.copyLink': { en: 'Copy Link', pt: 'Copiar Link' },
  'event.share.copySuccess': { en: 'Link copied to clipboard!', pt: 'Link copiado para a área de transferência!' },
  'event.share.orShareToFeed': { en: 'or share to feed', pt: 'ou compartilhe no feed' },
  'event.share.preview': { en: 'Event Preview', pt: 'Pré-visualização do Evento' },
  'event.share.placeholder': { en: 'Say something about this event...', pt: 'Diga algo sobre este evento...' },
  'event.share.loginToShare': { en: 'Please login to share to feed', pt: 'Por favor, faça login para compartilhar no feed' },
  'event.share.success': { en: 'Shared to feed successfully!', pt: 'Compartilhado no feed com sucesso!' },
  'event.share.failed': { en: 'Failed to share to feed', pt: 'Falha ao compartilhar no feed' },
  'event.share.toMotorFeed': { en: 'Share to MotorFeed', pt: 'Compartilhar no MotorFeed' },

  // My Events Page
  'myEvents.title': { en: 'My Events', pt: 'Meus Eventos' },
  'myEvents.subtitle': { en: 'Events you\'re hosting or attending.', pt: 'Eventos que você está organizando ou participando.' },
  'myEvents.hosting': { en: 'Hosting', pt: 'Organizando' },
  'myEvents.attending': { en: 'Attending', pt: 'Participando' },
  'myEvents.noEvents': { en: 'No Events Yet', pt: 'Nenhum Evento Ainda' },
  'myEvents.noEventsDesc': { en: 'You haven\'t created or RSVP\'d to any events.', pt: 'Você ainda não criou nem confirmou presença em nenhum evento.' },
  'myEvents.browse': { en: 'Browse Events', pt: 'Ver Eventos' },

  // Login
  'login.enter': { en: 'Enter Café777.app', pt: 'Entrar no Café777.app' },
  'login.skip': { en: 'Skip Intro', pt: 'Pular Intro' },
  'login.welcome': { en: 'Welcome Back', pt: 'Bem-vindo de volta' },
  'login.subtitle': { en: 'Login to Café777', pt: 'Entre no Café777' },
  'login.email': { en: 'Email Address', pt: 'Endereço de E-mail' },
  'login.password': { en: 'Password', pt: 'Senha' },
  'login.noAccount': { en: 'Don\'t have an account?', pt: 'Não tem uma conta?' },
  'login.admin': { en: 'Administrator Access', pt: 'Acesso Administrativo' },
  'login.orContinueWith': { en: 'Or continue with', pt: 'Ou continue com' },

  // Register
  'register.subtitle': { en: 'Create your unique profile page', pt: 'Crie sua página de perfil única' },
  'register.type.rider': { en: 'Rider', pt: 'Motociclista' },
  'register.type.ecosystem': { en: 'Ecosystem', pt: 'Ecossistema' },
  'register.username': { en: 'Username (URL)', pt: 'Nome de Usuário (URL)' },
  'register.fullName': { en: 'Full Name', pt: 'Nome Completo' },
  'register.age': { en: 'Age', pt: 'Idade' },
  'register.city': { en: 'City', pt: 'Cidade' },
  'register.companyName': { en: 'Company Name', pt: 'Nome da Empresa' },
  'register.category': { en: 'Category', pt: 'Categoria' },
  'register.address': { en: 'Full Address', pt: 'Endereço Completo' },
  'register.bio': { en: 'Details / Bio', pt: 'Detalhes / Bio' },
  'register.create': { en: 'Create Profile', pt: 'Criar Perfil' },
  'register.success': { en: 'Registration Received!', pt: 'Registro Recebido!' },
  'register.successDesc': { en: 'Thank you for joining the Café777 Ecosystem. Your registration is currently pending administrator approval. We will review your application and activate your account shortly.', pt: 'Obrigado por se juntar ao Ecossistema Café777. Seu registro está pendente de aprovação do administrador. Analisaremos sua solicitação e ativaremos sua conta em breve.' },
  'register.backToLogin': { en: 'Back to Login', pt: 'Voltar para o Login' },

  // Auth (legacy/shared)
  'auth.login.title': { en: 'Welcome Back', pt: 'Bem-vindo de volta' },
  'auth.login.subtitle': { en: 'Sign in to your account', pt: 'Entre na sua conta' },
  'auth.register.title': { en: 'Join the Community', pt: 'Junte-se à Comunidade' },
  'auth.register.subtitle': { en: 'Create your account', pt: 'Crie sua conta' },
  'auth.field.username': { en: 'Username', pt: 'Usuário' },
  'auth.field.password': { en: 'Password', pt: 'Senha' },
  'auth.btn.login': { en: 'Sign In', pt: 'Entrar' },
  'auth.btn.register': { en: 'Create Account', pt: 'Criar Conta' },
  'auth.noAccount': { en: 'Don\'t have an account?', pt: 'Não tem uma conta?' },
  'auth.hasAccount': { en: 'Already have an account?', pt: 'Já tem uma conta?' },

  // Common
  'locale': { en: 'en-US', pt: 'pt-BR' },
  'common.cancel': { en: 'Cancel', pt: 'Cancelar' },
  'common.linkCopied': { en: 'Link copied to clipboard!', pt: 'Link copiado!' },
  'common.ends': { en: 'Ends', pt: 'Termina' },
  'common.viewDetails': { en: 'View Details', pt: 'Ver Detalhes' },
  'common.post': { en: 'Post', pt: 'Postar' },
  'common.none': { en: 'None', pt: 'Nenhum' },
  'common.save': { en: 'Save Changes', pt: 'Salvar Alterações' },
  'common.saving': { en: 'Saving...', pt: 'Salvando...' },
  'common.loading': { en: 'Loading...', pt: 'Carregando...' },
  'common.search': { en: 'Search...', pt: 'Buscar...' },
  'common.close': { en: 'Close', pt: 'Fechar' },
  'common.submit': { en: 'Submit', pt: 'Enviar' },
  'common.submitting': { en: 'Submitting...', pt: 'Enviando...' },
  'common.delete': { en: 'Delete', pt: 'Excluir' },
  'common.edit': { en: 'Edit', pt: 'Editar' },
  'common.back': { en: 'Back', pt: 'Voltar' },
  'common.next': { en: 'Next', pt: 'Próximo' },
  'common.finish': { en: 'Finish', pt: 'Finalizar' },
  'common.error': { en: 'Error', pt: 'Erro' },
  'common.success': { en: 'Success', pt: 'Sucesso' },
  'common.verified': { en: 'Verified', pt: 'Verificado' },
  'common.unverified': { en: 'Unverified', pt: 'Não Verificado' },
  'common.scan': { en: 'Scan', pt: 'Escanear' },
  'common.scanner': { en: 'Scanner', pt: 'Scanner' },
  'common.qrCode': { en: 'QR Code', pt: 'Código QR' },
  'common.simulate': { en: 'Simulate', pt: 'Simular' },
  'common.history': { en: 'History', pt: 'Histórico' },
  'common.na': { en: 'N/A', pt: 'N/D' },

  // Reviews
  'review.noFound': { en: 'No reviews found', pt: 'Nenhuma avaliação encontrada' },
  'review.leave': { en: 'Leave a Review', pt: 'Deixar uma Avaliação' },
  'review.all': { en: 'All Reviews', pt: 'Todas as Avaliações' },
  'review.submit': { en: 'Submit Review', pt: 'Enviar Avaliação' },
  'review.submitting': { en: 'Submitting...', pt: 'Enviando...' },
  'review.verified': { en: 'Verified', pt: 'Verificado' },
  'review.unverified': { en: 'Unverified', pt: 'Não Verificado' },
  'review.completeToVerify': { en: 'Complete route to verify', pt: 'Complete a rota para verificar' },
  'review.scanLocation': { en: 'Scan Location QR Code', pt: 'Escanear QR Code do Local' },
  'review.simulate': { en: 'Simulate', pt: 'Simular' },
  'review.qrMismatch': { en: 'QR code does not match this location.', pt: 'O QR code não corresponde a este local.' },
  'review.failed': { en: 'Verification failed on server.', pt: 'A verificação falhou no servidor.' },
  'review.invalidQR': { en: 'Invalid QR code format.', pt: 'Formato de QR code inválido.' },

  // Scanner
  'scanner.title': { en: 'Scanner', pt: 'Scanner' },
  'scanner.subtitle': { en: 'Scan Ambassador QR codes to collect stamps or verify checkpoints.', pt: 'Escaneie QR codes de Embaixadores para coletar selos ou verificar checkpoints.' },
  'scanner.desc': { en: 'Scan Ambassador QR codes to collect stamps or verify checkpoints.', pt: 'Escaneie QR codes de Embaixadores para coletar selos ou verificar checkpoints.' },
  'scanner.loginRequired': { en: 'Please login to scan QR codes', pt: 'Por favor, faça login para escanear códigos QR' },
  'scanner.stampCollected': { en: 'Passport stamp collected!', pt: 'Selo do passaporte coletado!' },
  'scanner.checkpointVerified': { en: 'Checkpoint verified successfully!', pt: 'Checkpoint verificado com sucesso!' },
  'scanner.failed': { en: 'Scan failed. Please try again.', pt: 'Falha no escaneamento. Tente novamente.' },
  'scanner.verified': { en: 'Checkpoint Verified!', pt: 'Checkpoint Verificado!' },
  'scanner.collect': { en: 'Scan to Collect', pt: 'Escanear para Coletar' },
  'scanner.verify': { en: 'Scan to verify', pt: 'Escanear para verificar' },
  'scanner.stop': { en: 'Stop Scan', pt: 'Parar Scan' },
  'scanner.scanQR': { en: 'Scan QR', pt: 'Escanear QR' },

  // Contest
  'contest.submit': { en: 'Submit Entry', pt: 'Enviar Inscrição' },
  'contest.yourShot': { en: 'Your Shot', pt: 'Sua Foto' },
  'contest.submittedBy': { en: 'Submitted by', pt: 'Enviado por' },
  'contest.submitEntry': { en: 'Submit Entry', pt: 'Enviar Inscrição' },
  'contest.loginToVote': { en: 'Please login to vote', pt: 'Por favor, faça login para votar' },
  'contest.voteCounted': { en: 'Vote counted!', pt: 'Voto contabilizado!' },
  'contest.commentAdded': { en: 'Comment added!', pt: 'Comentário adicionado!' },
  'contest.uploadSuccess': { en: 'Photo submitted for contest!', pt: 'Foto enviada para o concurso!' },
  'contest.noActive': { en: 'No active photo contests right now.', pt: 'Nenhum concurso de fotos ativo no momento.' },
  'contest.active': { en: 'Active Contest', pt: 'Concurso Ativo' },
  'contest.title': { en: 'Photo Contest', pt: 'Concurso de Fotos' },
  'contest.subtitle': { en: 'Show off your ride and win exclusive prizes.', pt: 'Mostre sua moto e ganhe prêmios exclusivos.' },
  'contest.leaderboard': { en: 'Leaderboard', pt: 'Líderes' },
  'contest.submissions': { en: 'Submissions', pt: 'Submissões' },
  'contest.votes': { en: 'Votes', pt: 'Votos' },
  'contest.noDescription': { en: 'No description provided', pt: 'Nenhuma descrição fornecida' },
  'contest.taggedRide': { en: 'Tagged Ride', pt: 'Moto Marcada' },
  'contest.vote': { en: 'Vote', pt: 'Votar' },
  'contest.comments': { en: 'Comments', pt: 'Comentários' },
  'contest.addComment': { en: 'Add a comment...', pt: 'Adicione um comentário...' },
  'contest.clickToUpload': { en: 'Click to upload photo', pt: 'Clique para enviar foto' },
  'contest.tellUs': { en: 'Tell us about this shot...', pt: 'Conte-nos sobre esta foto...' },
  'contest.bgAlt': { en: 'Contest Background', pt: 'Fundo do Concurso' },
  'contest.submissionAlt': { en: 'Submission', pt: 'Submissão' },
  'contest.submissionDetailAlt': { en: 'Submission Detail', pt: 'Detalhe da Submissão' },
  'contest.previewAlt': { en: 'Preview', pt: 'Prévia' },

  // Profile / Garage
  'profile.newMaintenance': { en: 'New Maintenance Entry', pt: 'Novo Registro de Manutenção' },
  'profile.logs': { en: 'Logs', pt: 'Registros' },
  'profile.viewAllHistory': { en: 'View All History', pt: 'Ver Todo o Histórico' },
  'profile.noMaintenance': { en: 'No maintenance history', pt: 'Sem histórico de manutenção' },
  'profile.editEvent': { en: 'Edit Event', pt: 'Editar Evento' },
  'profile.createNewEvent': { en: 'Create New Event', pt: 'Criar Novo Evento' },
  'profile.eventTitle': { en: 'Event Title', pt: 'Título do Evento' },
  'profile.eventTimePlaceholder': { en: 'Time (e.g. 08:00 AM)', pt: 'Hora (ex: 08:00)' },
  'profile.eventLocation': { en: 'Location', pt: 'Localização' },
  'profile.eventImage': { en: 'Event Image', pt: 'Imagem do Evento' },
  'profile.upload': { en: 'Upload', pt: 'Enviar' },
  'profile.uploadDesc': { en: 'Upload a cover image for your event. Recommended size: 1200x600px.', pt: 'Envie uma imagem de capa para o seu evento. Tamanho recomendado: 1200x600px.' },
  'profile.removeImage': { en: 'Remove Image', pt: 'Remover Imagem' },
  'profile.eventDescription': { en: 'Event Description', pt: 'Descrição do Evento' },
  'profile.updating': { en: 'Updating...', pt: 'Atualizando...' },
  'profile.creating': { en: 'Creating...', pt: 'Criando...' },
  'profile.updateEvent': { en: 'Update Event', pt: 'Atualizar Evento' },
  'profile.publishEvent': { en: 'Publish Event', pt: 'Publicar Evento' },
  'profile.category': { en: 'Category', pt: 'Categoria' },
  'profile.address': { en: 'Address', pt: 'Endereço' },
  'profile.tagBike': { en: 'Tag Bike', pt: 'Marcar Moto' },
  'profile.public': { en: 'Public', pt: 'Público' },
  'profile.followersOnly': { en: 'Followers Only', pt: 'Apenas Seguidores' },
  'profile.pinned': { en: 'Pinned', pt: 'Fixado' },
  'profile.eventLabel': { en: 'Event', pt: 'Evento' },
  'profile.savingLog': { en: 'Saving Log...', pt: 'Salvando Registro...' },
  'profile.recentHistory': { en: 'Recent History', pt: 'Histórico Recente' },
  'profile.postSuccess': { en: 'Post created successfully!', pt: 'Post criado com sucesso!' },
  'profile.postFailed': { en: 'Failed to create post', pt: 'Falha ao criar post' },
  'profile.postError': { en: 'An error occurred while creating post', pt: 'Ocorreu um erro ao criar o post' },
  'profile.pinSuccess': { en: 'Post pinned to top!', pt: 'Post fixado no topo!' },
  'profile.unpinSuccess': { en: 'Post unpinned', pt: 'Post desfixado' },
  'profile.pinFailed': { en: 'Failed to pin post', pt: 'Falha ao fixar post' },
  'profile.pinError': { en: 'An error occurred while pinning post', pt: 'Ocorreu um erro ao fixar o post' },
  'profile.eventTitleRequired': { en: 'Title is required', pt: 'Título é obrigatório' },
  'profile.eventDateRequired': { en: 'Date is required', pt: 'Data é obrigatória' },
  'profile.eventTimeRequired': { en: 'Time is required', pt: 'Hora é obrigatória' },
  'profile.eventSuccess': { en: 'Event created successfully!', pt: 'Evento criado com sucesso!' },
  'profile.eventFailed': { en: 'Failed to create event', pt: 'Falha ao criar evento' },
  'profile.ambassador': { en: 'Ambassador', pt: 'Embaixador' },
  'profile.reputation': { en: 'Reputation', pt: 'Reputação' },
  'profile.referrals': { en: 'Referrals', pt: 'Indicações' },
  'profile.followers': { en: 'Followers', pt: 'Seguidores' },
  'profile.following': { en: 'Following', pt: 'Seguindo' },
  'profile.more': { en: 'MORE', pt: 'MAIS' },
  'profile.follow': { en: 'Follow', pt: 'Seguir' },
  'profile.unfollow': { en: 'Unfollow', pt: 'Deixar de Seguir' },
  'profile.bikerPassport': { en: 'Biker Passport', pt: 'Passaporte Motociclista' },
  'profile.passport': { en: 'Passport', pt: 'Passaporte' },
  'profile.allTabs': { en: 'All Tabs', pt: 'Todas as Abas' },
  'profile.navigation': { en: 'Navigation', pt: 'Navegação' },
  'profile.accessDenied': { en: 'Access Denied', pt: 'Acesso Negado' },
  'profile.noPermissionEdit': { en: 'You do not have permission to edit this profile.', pt: 'Você não tem permissão para editar este perfil.' },
  'profile.uploadNewPhoto': { en: 'Click the camera to upload a new photo', pt: 'Clique na câmera para enviar uma nova foto' },
  'profile.picUrl': { en: 'Profile Picture URL', pt: 'URL da Foto de Perfil' },
  'profile.username': { en: 'Username', pt: 'Nome de Usuário' },
  'profile.fullName': { en: 'Full Name', pt: 'Nome Completo' },
  'profile.age': { en: 'Age', pt: 'Idade' },
  'profile.city': { en: 'City', pt: 'Cidade' },
  'profile.companyName': { en: 'Company Name', pt: 'Nome da Empresa' },
  'profile.fullAddress': { en: 'Full Address', pt: 'Endereço Completo' },
  'profile.detailsBio': { en: 'Details / Bio', pt: 'Detalhes / Bio' },
  'profile.garageManagement': { en: 'Garage Management', pt: 'Gerenciamento da Garagem' },
  'profile.addMaintenanceLog': { en: 'Add Maintenance Log', pt: 'Adicionar Registro de Manutenção' },
  'profile.servicePerformed': { en: 'Service Performed', pt: 'Serviço Realizado' },
  'profile.servicePlaceholder': { en: 'e.g. Oil Change, Tire Replacement', pt: 'ex: Troca de Óleo, Troca de Pneu' },
  'profile.currentKm': { en: 'Current KM', pt: 'KM Atual' },
  'profile.kmPlaceholder': { en: 'KM', pt: 'KM' },
  'profile.shopLocation': { en: 'Shop / Location', pt: 'Oficina / Local' },
  'profile.shopPlaceholder': { en: 'Shop Name', pt: 'Nome da Oficina' },
  'profile.saveMaintenanceLog': { en: 'Save Maintenance Log', pt: 'Salvar Registro de Manutenção' },

  // Profile / Post Actions
  'profile.respect': { en: 'Respect', pt: 'Respeito' },
  'profile.pinPost': { en: 'Pin post to top', pt: 'Fixar post no topo' },
  'profile.unpinPost': { en: 'Unpin post', pt: 'Desfixar post' },
  'profile.pin': { en: 'Pin', pt: 'Fixar' },
  'profile.unpin': { en: 'Unpin', pt: 'Desfixar' },

  // Profile / Achievements
  'profile.by': { en: 'By', pt: 'Por' },
  'profile.platform': { en: 'Platform', pt: 'Plataforma' },
  'profile.noAchievements': { en: 'No achievements yet.', pt: 'Nenhuma conquista ainda.' },
  'profile.earnedOn': { en: 'Earned On', pt: 'Conquistado em' },

  // Profile / Recommendations
  'profile.addNew': { en: 'Add New', pt: 'Adicionar Novo' },
  'profile.roadRoute': { en: 'Road Route', pt: 'Rota de Estrada' },
  'profile.shopPlace': { en: 'Shop / Place', pt: 'Loja / Local' },
  'profile.viewDetails': { en: 'View Details', pt: 'Ver Detalhes' },
  'profile.noRecommendations': { en: 'No recommendations found', pt: 'Nenhuma recomendação encontrada' },
  'profile.addNewRecommendation': { en: 'Add New Recommendation', pt: 'Adicionar Nova Recomendação' },
  'profile.type': { en: 'Type', pt: 'Tipo' },
  'profile.itemId': { en: 'Item ID', pt: 'ID do Item' },
  'profile.itemIdPlaceholder': { en: 'e.g. route-123', pt: 'ex: rota-123' },
  'profile.name': { en: 'Name', pt: 'Nome' },
  'profile.displayName': { en: 'Display Name', pt: 'Nome de Exibição' },
  'profile.personalNote': { en: 'Personal Note', pt: 'Nota Pessoal' },
  'profile.personalNotePlaceholder': { en: 'Why do you recommend this?', pt: 'Por que você recomenda isso?' },
  'profile.publishRecommendation': { en: 'Publish Recommendation', pt: 'Publicar Recomendação' },

  // Profile / Passport
  'profile.passportStamps': { en: 'Passport Stamps', pt: 'Carimbos do Passaporte' },
  'profile.noStamps': { en: 'No Stamps Yet', pt: 'Nenhum Carimbo Ainda' },
  'profile.noStampsDesc': { en: 'Visit ambassadors and scan their QR codes to collect passport stamps.', pt: 'Visite embaixadores e escaneie seus códigos QR para coletar carimbos no passaporte.' },
  'profile.issuedBy': { en: 'Issued By', pt: 'Emitido Por' },
  'profile.date': { en: 'Date', pt: 'Data' },

  // Club Management
  'club.mgmt.overview': { en: 'Overview', pt: 'Visão Geral' },
  'club.mgmt.members': { en: 'Members', pt: 'Membros' },
  'club.mgmt.roles': { en: 'Roles', pt: 'Cargos' },
  'club.mgmt.chapters': { en: 'Chapters', pt: 'Facções' },
  'club.mgmt.pendingApps': { en: 'Pending Applications', pt: 'Solicitações Pendentes' },
  'club.mgmt.noPending': { en: 'No pending applications.', pt: 'Nenhuma solicitação pendente.' },
  'club.mgmt.recentMembers': { en: 'Recent Members', pt: 'Membros Recentes' },
  'club.mgmt.assignRole': { en: 'Assign Role', pt: 'Atribuir Cargo' },
  'club.mgmt.noRole': { en: 'No Role', pt: 'Sem Cargo' },
  'club.mgmt.leaveClub': { en: 'Leave Club', pt: 'Sair do Clube' },
  'club.mgmt.newRole': { en: 'New Role', pt: 'Novo Cargo' },
  'club.mgmt.roleName': { en: 'Role Name', pt: 'Nome do Cargo' },
  'club.mgmt.roleDesc': { en: 'Description', pt: 'Descrição' },
  'club.mgmt.saveRole': { en: 'Save Role', pt: 'Salvar Cargo' },
  'club.mgmt.deleteRoleConfirm': { en: 'Are you sure you want to delete this role?', pt: 'Tem certeza que deseja excluir este cargo?' },
  'club.mgmt.newChapter': { en: 'New Chapter', pt: 'Nova Facção' },
  'club.mgmt.chapterName': { en: 'Chapter Name', pt: 'Nome da Facção' },
  'club.mgmt.city': { en: 'City', pt: 'Cidade' },
  'club.mgmt.country': { en: 'Country', pt: 'País' },
  'club.mgmt.saveChapter': { en: 'Save Chapter', pt: 'Salvar Facção' },
  'club.mgmt.deleteChapterConfirm': { en: 'Are you sure you want to delete this chapter?', pt: 'Tem certeza que deseja excluir esta facção?' },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'pt';
  });

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string, params?: Record<string, string | number>) => {
    if (!translations[key]) {
      console.warn(`Translation key not found: ${key}`);
      return key;
    }
    let text = translations[key][language];
    if (params) {
      Object.entries(params).forEach(([k, v]) => {
        text = text.replace(`{${k}}`, String(v));
      });
    }
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
